[package]
name = "rsnano-insight"
version = "0.1.0"
edition = "2024"

[features]
ledger_snapshots = [
	"rsnano_node/ledger_snapshots",
	"rsnano_daemon/ledger_snapshots",
]

[dependencies]
eframe = "0.33.2"
egui_extras = "0.33.2"
rsnano_nullable_clock = { path = "../../nullables/clock" }
rsnano_nullable_tracing_subscriber = { path = "../../nullables/tracing_subscriber" }
rsnano_types = { path = "../../types" }
rsnano_utils = { path = "../../utils" }
rsnano_messages = { path = "../../messages" }
rsnano_network = { path = "../../network" }
rsnano_store_lmdb = { path = "../../store_lmdb" }
rsnano_node = { path = "../../node" }
rsnano_daemon = { path = "../../daemon" }
rsnano_ledger = { path = "../../ledger" }
tokio = { version = "1", features = ["rt-multi-thread"] }
num-format = "0.4.4"
num = "0"
num-traits = "0"
num-derive = "0"
chrono = "0.4.42"
strum = "0"
tracing = "0"
serde_json = "1"
