[package]
name = "rsnano_nullable_tracing_subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
rsnano_nullable_env = { path = "../env" }
rsnano_output_tracker = { path = "../output_tracker" }
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
