[package]
name = "rsnano_node"
version = "2.0.0-dev"
authors = ["Gustav Schauwecker <service@simpago.com>"]
edition = "2024"

[features]
output_tracking = []
ledger_snapshots = [
	"rsnano_messages/ledger_snapshots", 
	"rsnano_network/ledger_snapshots", 
	"rsnano_network_protocol/ledger_snapshots",
	"rsnano_utils/ledger_snapshots",
	"rsnano_store_lmdb/ledger_snapshots",
	"rsnano_ledger/ledger_snapshots",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsnano_types = { path = "../types" }
rsnano_work = { path = "../work" }
rsnano_utils = { path = "../utils" }
rsnano_messages = { path = "../messages" }
rsnano_network = { path = "../network" }
rsnano_network_protocol = { path = "../network_protocol" }
rsnano_store_lmdb = { path = "../store_lmdb" }
rsnano_output_tracker = { path = "../nullables/output_tracker" }
rsnano_wallet = { path = "../wallet" }
rsnano_nullable_fs = { path = "../nullables/fs" }
rsnano_nullable_tcp = { path = "../nullables/tcp" }
rsnano_nullable_lmdb = { path = "../nullables/lmdb" }
rsnano_nullable_clock = { path = "../nullables/clock" }
rsnano_nullable_random = { path = "../nullables/random" }
rsnano_nullable_http_client = { path = "../nullables/http_client" }
rsnano_nullable_env = { path = "../nullables/env" }
rsnano_ledger = { path = "../ledger" }
rsnano_websocket_messages = { path = "../websocket/messages" }
anyhow = "1"
bitvec = "1"
blake2 = "0.10.6"
bounded-vec-deque = "0"
chrono = "0"
dirs = "6"
num = "0"
num-derive = "0"
num-traits = "0.2.19"
once_cell = "1"
rand = { version = "0.9.2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
static_assertions = "1"
toml_edit = "0"
uuid = { version = "1", features = ["v4"] }
serde_variant = "0"
primitive-types = "0"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
    "sync",
] }
async-trait = "0"
tracing = "0"
ordered-float = "5"
tokio-tungstenite = "0"
futures-util = { version = "0", features = ["sink"] }
tokio-util = "0"
toml = "0"
strum = "0.27.2"
strum_macros = "0"
build-info = "0.0.42"
num-format = "0.4.4"
rustc-hash = "2.1.1"
const_format = "0.2.35"

[dev-dependencies]
mock_instant = "0"
tracing-test = "0"
test_helpers = { path = "../tools/test_helpers" }
ntest = "0.9.3"

[build-dependencies]
build-info-build = "0.0.42"
