[package]
name = "nanospam"
version = "0.1.0"
edition = "2024"

[dependencies]
rsnano_nullable_clock = { path = "../../nullables/clock" }
rsnano_nullable_tcp = { path = "../../nullables/tcp" }
rsnano_nullable_tracing_subscriber = { path = "../../nullables/tracing_subscriber" }
rsnano_nullable_env = { path = "../../nullables/env" }
rsnano_types = { path = "../../types" }
rsnano_utils = { path = "../../utils" }
rsnano_messages = { path = "../../messages" }
rsnano_network = { path = "../../network" }
rsnano_network_protocol = { path = "../../network_protocol" }
rsnano_websocket_messages = { path = "../../websocket/messages" }
rsnano_websocket_client = { path = "../../websocket/client" }
rsnano_rpc_client = { path = "../../rpc/client" }
rsnano_rpc_messages = { path = "../../rpc/messages" }
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread", "net", "io-util"] }
tokio-scoped = "0.2.0"
tracing = "0.1.41"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9.2"
tokio-util = "0.7.17"
dirs = "6.0.0"
clap = { version = "4.5.53", features = ["derive"] }
rustc-hash = "2.1.1"
num-format = "0.4.4"

[dev-dependencies]
ntest = "0.9.3"
