[package]
name = "rsnano_work"
version = "0.1.0"
edition = "2024"

[features]
opencl = ["dep:ocl"]

[dependencies]
rsnano_types = { path = "../types" }
rsnano_utils = { path = "../utils" }
tracing = "0"
ocl = { version = "0.19", optional = true }
rand = { version = "0.9" }
serde_json = "1"
